apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "auto-passport.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "auto-passport.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: view-all-namespaces
  apiGroup: rbac.authorization.k8s.io



