package utils

import (
	"log"
	"os"

	"gopkg.in/yaml.v2"
)

var CONFIG_PATH string = "config.yaml"

// generated by https://zhwt.github.io/yaml-to-go/
type Config struct {
	StaticTargets struct {
		Airflow  []string `yaml:"airflow"`
		Metabase []string `yaml:"metabase"`
		Superset []string `yaml:"superset"`
	} `yaml:"static_targets"`
}

func ReadConfig(section string) []string {
	yamlFile, err := os.ReadFile(CONFIG_PATH)
	if err != nil {
		log.Fatalf("Error reading config file: %v", err)
	}

	var config Config
	err = yaml.Unmarshal(yamlFile, &config)
	if err != nil {
		log.Fatalf("Error parsing config file: %v", err)
	}

	switch section {
	case "airflow":
		return config.StaticTargets.Airflow
	case "metabase":
		return config.StaticTargets.Metabase
	case "superset":
		return config.StaticTargets.Superset
	default:
		return nil
	}
}
