package utils

import (
	"log"
	"os"

	"gopkg.in/yaml.v2"
)

var CONFIG_PATH string = "config.yaml"

type ConfigInterface interface {
	ReadConfig()
	GetConfig() *Config
}

// generated by https://zhwt.github.io/yaml-to-go/
type Config struct {
	StaticTargets struct {
		Airflow  []string `yaml:"airflow"`
		Metabase []string `yaml:"metabase"`
		Superset []string `yaml:"superset"`
	} `yaml:"static_targets"`
	Cluster string `yaml:"cluster"`
}

func (config *Config) ReadConfig() {
	// config := &Config{}

	yamlFile, err := os.ReadFile(CONFIG_PATH)
	if err != nil {
		log.Fatalf("Error reading config file: %v", err)
	}

	err = yaml.Unmarshal(yamlFile, &config)
	if err != nil {
		log.Fatalf("Error parsing config file: %v", err)
	}

	// return config
}

func (config *Config) GetConfig() *Config {
	return config
}
